OUTPUT_ARCH(riscv)
ENTRY(_start)

BASE_ADDRESS = 0x0;

SECTIONS
{
    . = BASE_ADDRESS;
    
    .text : {
        *(.text.entry)
        *(.text .text.*)
    }
    
    .rodata : {
        *(.rodata .rodata.*)
    }
    
    .data : {
        *(.data .data.*)
        *(.sdata .sdata.*)
    }
    
    .bss : {
        *(.bss .bss.*)
        *(.sbss .sbss.*)
    }
    
    /DISCARD/ : {
        *(.eh_frame)
    }
}